services:
  client:
    container_name: solidhive-client
    build:
      context: ./client
      dockerfile: Dockerfile
      target: prod-runner
      args:
        NODE_ENV: production
    environment:
      - VITE_HOST=0.0.0.0
    volumes:
      - ./client/package.json:/usr/src/app/package.json
    depends_on:
      - server
    networks:
      - app-network

  server:
    container_name: solidhive-server
    build:
      context: ./server
      dockerfile: Dockerfile
      target: prod-runner
      args:
        NODE_ENV: production
    env_file:
      - ./server/.env.prod
    volumes:
      - ./server/migrations:/usr/src/app/migrations
      - ./server/package.json:/usr/src/app/package.json
      - ./server/logs:/usr/src/app/logs
      - ./server/uploads:/usr/src/app/uploads
    depends_on:
      - db
    networks:
      - app-network

  db:
    container_name: solidhive-db
    image: postgres:16
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=solidhive
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  redis:
    container_name: solidhive-redis
    image: redis:7-alpine
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis_data:/data
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: solidhive-nginx
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    depends_on:
      - client
      - server
    networks:
      - app-network

  certbot:
    image: certbot/certbot
    container_name: solidhive-certbot
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    networks:
      - app-network

volumes:
  db_data:
  redis_data:

networks:
  app-network:
    driver: bridge