# 1. HTTP : ACME + redirection vers HTTPS pour tous les domaines
server {
    listen 80;
    server_name lucas.madranges.lille.mds-project.fr

    # Challenge Let's Encrypt
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    # Redirige tout le reste en HTTPS
    location / {
        return 301 https://$host$request_uri;
    }
}

# 2. HTTPS pour le frontend (main domain)
server {
    listen 443 ssl;
    server_name lucas.madranges.lille.mds-project.fr;

    ssl_certificate     /etc/letsencrypt/live/lucas.madranges.lille.mds-project.fr/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/lucas.madranges.lille.mds-project.fr/privkey.pem;

    # SPA / frontend
    location / {
        proxy_pass http://client:80;
        proxy_set_header Host      $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}

