version = 5.2.2
archive_dir = /etc/letsencrypt/archive/theotime.pagies.lille.mds-project.fr
cert = /etc/letsencrypt/live/theotime.pagies.lille.mds-project.fr/cert.pem
privkey = /etc/letsencrypt/live/theotime.pagies.lille.mds-project.fr/privkey.pem
chain = /etc/letsencrypt/live/theotime.pagies.lille.mds-project.fr/chain.pem
fullchain = /etc/letsencrypt/live/theotime.pagies.lille.mds-project.fr/fullchain.pem
[renewalparams]
account = 25e26cfda77b92d797d444e8a10e4492
authenticator = webroot
webroot_path = /var/www/certbot,
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
[[webroot_map]]
theotime.pagies.lille.mds-project.fr = /var/www/certbot
