export enum Permissions {
  ALL = '*',
  ROLES_CREATE = 'roles_create',
  ROLES_DELETE = 'roles_delete',
  ROLES_UPDATE = 'roles_update',
  ROLES_VIEW = 'roles_view',
  EVENTS_CREATE = 'events_create',
  EVENTS_DELETE = 'events_delete',
  EVENTS_UPDATE = 'events_update',
  REGISTERS_CREATE = 'registers_create',
  REGISTERS_DELETE = 'registers_delete',
  REGISTERS_UPDATE = 'registers_update',
  REGISTERS_VIEW = 'registers_view',
  FUNDRAISINGS_CREATE = 'fundraisings_create',
  FUNDRAISINGS_DELETE = 'fundraisings_delete',
  FUNDRAISINGS_UPDATE = 'fundraisings_update',
  ANNOUNCEMENTS_CREATE = 'announcements_create',
  ANNOUNCEMENTS_DELETE = 'announcements_delete',
  ANNOUNCEMENTS_UPDATE = 'announcements_update',
  ASSOCIATION_UPDATE = 'association_update',
  ASSOCIATION_REMOVE = 'association_remove',
  STATISTICS_VIEW = 'statistics_view',
}
